# IMC channel-ib 설정

imc:
    channel:
        ib:
            # 시뮬레이션 발송 모드
            simulation: true
            # 시뮬레이션 delay time (ms)
            simulation-delay-millis: 25
            # embp 접속정보
            embp:
                host: embp.ibizplus.co.kr
                port: 9214
                id: imc_test01
                password: LPWX3A2YD8XOJ110CG06
            # send line 실행 여부
            send-run: true
            # report line 실행 여부
            report-run: true
            # tcp dump 출력 여부
            show-packet-dump: true
            # heartbeat interval 시간 설정
            heartbeat-interval: 60
            # cron schedule 정보
            cron:
                load-client-info: 10 */10 * * * *

endpoints:
    shutdown:
        sensitive: false
        enabled: true

logging:
    config: logback-spring.xml

spring:
    # kafka 설정
    # https://kafka.apache.org/documentation/#consumerconfigs
    # https://kafka.apache.org/documentation/#producerconfigs
    kafka:
        # Kafka 서버 (여러개일 경우, 콤마로 분리)
        bootstrap-servers: 211.48.18.171:9092
        # producer 설정
        producer:
            retries: 0
            batch-size: 20000
            compression-type: gzip
            linger-ms: 50
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: channel-ib-consumer-group
            enable-auto-commit: false
            max-poll-records: 500
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        listener:
            concurrency: 10
            ack-mode: MANUAL_IMMEDIATE
            poll-timeout: 3000
            batch: false
