# IMC relay 공통 설정
imc:
    relay:
        # Kafka 설정. 기타 설정은 개별 프로세스에서 별도로 설정해서 사용한다.
        kafka:
            # Kafka 서버 (여러개일 경우, 콤마로 분리)
            bootstrap-servers: 211.48.18.171:9092
            # Kafka consumer 공통 설정
            # 각 설정은 아래 사이트를 통해 확인할 수 있다.
            # https://kafka.apache.org/documentation/#consumerconfigs
            consumer:
                # key deserializer class
                key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                # value deserializer class
                value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            # Kafka producer 공통 설정
            # 각 설정은 아래 사이트를 통해 확인할 수 있다.
            # https://kafka.apache.org/documentation/#producerconfigs
            producer:
                batch-size: 20000
                buffer-memory: 33554432
                compression-type: gzip
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: org.apache.kafka.common.serialization.StringSerializer
spring:
    redis:
        host: 211.48.18.171
        password: humuson0722
        port: 6379
