# IMC loadbalancer 설정
imc:
    lb:
        cron:
            load-client-info: 10 */10 * * * *
            load-at-send-profile-info: 40 */10 * * * *
            load-at-template-info: 40 */10 * * * *
            load-send-group-info: 10 */10 * * * *

endpoints:
    shutdown:
        sensitive: false
        enabled: true

logging:
    config: logback-spring.xml

spring:
    # kafka 설정
    # https://kafka.apache.org/documentation/#consumerconfigs
    # https://kafka.apache.org/documentation/#producerconfigs
    kafka:
        # Kafka 서버 (여러개일 경우, 콤마로 분리)
        bootstrap-servers: 211.48.18.171:9092
        # producer 설정
        producer:
            retries: 0
            batch-size: 20000
            compression-type: gzip
            linger-ms: 50
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: lb-consumer-group
            enable-auto-commit: false
            max-poll-records: 500
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        listener:
            concurrency: 5
            ack-mode: MANUAL_IMMEDIATE
            poll-timeout: 3000

---

spring:
    profiles: dev

imc:
    lb:
        cron:
            load-client-info: 10 */10 * * * *
            load-at-send-profile-info: 40 */10 * * * *
            load-at-template-info: 40 */10 * * * *
            load-send-group-info: 10 */10 * * * *

---

spring:
    profiles: local

imc:
    lb:
        cron:
            load-client-info: 10 */10 * * * *
            load-at-send-profile-info: 40 */10 * * * *
            load-at-template-info: 40 */10 * * * *
            load-send-group-info: 10 */10 * * * *
            
