# IMC Relay 설정
imc:
    relay:
        # 실행 모드 : [Authorize, Message, Report, Store, All]
        run-mode: All
        # 인증서버 bind 포트
        authorize-port: 42000
        # MESSAGE 서버 bind 포트
        message-port: 42001
        # REPORT 서버 bind 포트
        report-port: 42002
        # TCP 옵션
        so-backlog: 1024
        so-keep-alive: true
        so-snd-buf: 1048576
        so-rcv-buf: 1048576
        so-reuse-addr: false
        tcp-no-delay: true
        # Netty 로깅 설정
        packet-print-dump: true
        filter-logging-remote-address-list:
            - 000.000.000.000

endpoints:
    shutdown:
        sensitive: false
        enabled: true

logging:
    config: logback-spring.xml

management:
    security:
        # enable security
        enabled: true

server:
    # Server HTTP port
    port: 32104

spring:
    # kafka 설정
    # https://kafka.apache.org/documentation/#consumerconfigs
    # https://kafka.apache.org/documentation/#producerconfigs
    kafka:
        # Kafka 서버 (여러개일 경우, 콤마로 분리)
        bootstrap-servers: 211.48.18.171:9092
        # producer 설정
        producer:
            retries: 0
            batch-size: 20000
            compression-type: gzip
            linger-ms: 50
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        # consumer 설정
        consumer:
            group-id: relay-consumer-group
            enable-auto-commit: false
            max-poll-records: 500
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        # listener 설정
        listener:
            concurrency: 1
            ack-mode: MANUAL_IMMEDIATE
            poll-timeout: 3000
            batch: false

---

spring:
    profiles: dev
  
imc:
    relay:
        run-mode: All

---

spring:
    profiles: local
  
imc:
    relay:
        run-mode: Message
