spring:
    # redis 설정
    redis:
        # redis 서버 (여러개일 경우, 콤마로 분리)
        host: 211.48.18.171
        # redis 접속 암호
        password: humuson0722
        # redis port
        port: 6379

---

spring:
    profiles: dev
    redis:
        host: 211.48.18.171
        password: humuson0722
        port: 6379

---

spring:
    profiles: local
    redis:
        host: 211.48.18.171
        password: humuson0722
        port: 6379
