# IMC store 설정
imc:
    store:
        cron:
            load-client-info: 0 */10 * * * *
            load-send-profile-info: 30 */10 * * * *
            load-at-template-info: 30 */10 * * * *
            load-send-group-info: 0 */30 * * * *
endpoints:
    shutdown:
        sensitive: false
        enabled: true
logging:
    config: logback-spring.xml
server:
    # Server HTTP port
    port: 42105
spring:
    # Database 설정
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            auto-commit: false
            connection-timeout: 60000
            maximum-pool-size: 10
        password: humuson0722
        url: jdbc:mysql://211.48.18.233:3306/imc?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true
        username: root
    # Enable JPA repositories
    data:
        jpa:
            repositories:
                enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: false
    # kafka 설정
    # https://kafka.apache.org/documentation/#consumerconfigs
    # https://kafka.apache.org/documentation/#producerconfigs
    kafka:
        # Kafka 서버 (여러개일 경우, 콤마로 분리)
        bootstrap-servers: 211.48.18.171:9092
        # producer 설정
        producer:
            retries: 0
            batch-size: 20000
            compression-type: gzip
            linger-ms: 50
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: store-consumer-group
            enable-auto-commit: false
            max-poll-records: 500
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        listener:
            concurrency: 10
            ack-mode: MANUAL_IMMEDIATE
            poll-timeout: 3000
            batch: true
---

spring:
    profiles: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            auto-commit: false
            connection-timeout: 60000
            maximum-pool-size: 10
        password: amail0722
        url: jdbc:mysql://119.207.76.94:3306/imc?autoReconnect=true&rewriteBatchedStatements=true
        username: root

---

spring:
    profiles: local
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            auto-commit: false
            connection-timeout: 60000
            maximum-pool-size: 10
        password: rlawlghks2$!
        url: jdbc:mysql://127.0.0.1:3306/imc?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true
        username: root
