# IMC channel-kakao 설정
################################################################################################################
# Kakao 비즈메시지 base-url 설정
#
# 휴머스온 운영
# 알림톡		: https://bzm-api.kakao.com/v1/990238b1219048cf5f2281a2f1ea5cb173a13ad6/sendMessage
# 친구톡		: https://bzm-api.kakao.com/v1/990238b1219048cf5f2281a2f1ea5cb173a13ad6/sendMessage
# 친구톡 이미지 : https://bzm-center.kakao.com/api/v1/990238b1219048cf5f2281a2f1ea5cb173a13ad6/ft/upload_image
#
# 휴머스온 테스트
# 알림톡		: https://dev-bzm-api.kakao.com/v1/990238b1219048cf5f2281a2f1ea5cb173a13ad6/sendMessage
# 친구톡		: https://dev-bzm-api.kakao.com/v1/990238b1219048cf5f2281a2f1ea5cb173a13ad6/sendMessage
# 친구톡 이미지 : https://dev-bzm-center.kakao.com/990238b1219048cf5f2281a2f1ea5cb173a13ad6/ft/upload_image
#
# 카카오 테스트
# 알림톡		: https://dev-bzm-api.kakao.com/v1/d856a846049ed4872e2b4664983539c2a6c7444f/sendMessage
# 친구톡		: https://dev-bzm-api.kakao.com/v1/d856a846049ed4872e2b4664983539c2a6c7444f/sendMessage
# 친구톡 이미지 : https://dev-bzm-center.kakao.com/api/v1/d856a846049ed4872e2b4664983539c2a6c7444f/ft/upload_image
################################################################################################################
imc:
    channel:
        kakao:
            # 시뮬레이션 발송 모드
            simulation: true
            # 시뮬레이션 delay time (ms)
            simulation-delay-millis: 25
            # url connection read-time 설정 (sec)
            read-timeout: 30
            # 알림톡 설정
            at:
                # 알림톡 실행 여부
                run: true
                # base url 설정
                base-url: https://dev-bzm-api.kakao.com/v1/d856a846049ed4872e2b4664983539c2a6c7444f/sendMessage
                # 알림톡 발송 topic list
                topics:
                    - send-at-01
                    - send-at-02
                    - send-at-03
                    - send-at-04
                    - send-at-05
            # 친구톡 설정
            ft:
                # 친구톡 실행 여부
                run: true
                # base url 설정
                base-url: https://dev-bzm-api.kakao.com/v1/d856a846049ed4872e2b4664983539c2a6c7444f/sendMessage
                # 이미지 url 설정
                img-url: https://dev-bzm-center.kakao.com/api/v1/d856a846049ed4872e2b4664983539c2a6c7444f/ft/upload_image
                # 친구톡 발송 topic list
                topics:
                    - send-ft-01
                    - send-ft-02
                    - send-ft-03
                    - send-ft-04
                    - send-ft-05

endpoints:
    shutdown:
        sensitive: false
        enabled: true

logging:
    config: logback-spring.xml

spring:
    # kafka 설정
    # https://kafka.apache.org/documentation/#consumerconfigs
    # https://kafka.apache.org/documentation/#producerconfigs
    kafka:
        # Kafka 서버 (여러개일 경우, 콤마로 분리)
        bootstrap-servers: 211.48.18.171:9092
        # producer 설정
        producer:
            retries: 0
            batch-size: 20000
            compression-type: gzip
            linger-ms: 50
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: channel-kakao-consumer-group
            enable-auto-commit: false
            max-poll-records: 500
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        listener:
            concurrency: 5
            ack-mode: MANUAL_IMMEDIATE
            poll-timeout: 3000
            batch: false
