# IMC relay 공통 설정
imc:
    common:
        # Kafka 설정. 기타 설정은 개별 프로세스에서 별도로 설정해서 사용한다.
        kafka:
            # Kafka 서버 (여러개일 경우, 콤마로 분리)
            bootstrap-servers: 211.48.18.171:9092
            # Kafka consumer 공통 설정
            # 각 설정은 아래 사이트를 통해 확인할 수 있다.
            # https://kafka.apache.org/documentation/#consumerconfigs
            consumer:
                # key deserializer class
                key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                # value deserializer class
                value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            # Kafka producer 공통 설정
            # 각 설정은 아래 사이트를 통해 확인할 수 있다.
            # https://kafka.apache.org/documentation/#producerconfigs
            producer:
                batch-size: 20000
                buffer-memory: 33554432
                compression-type: gzip
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: org.apache.kafka.common.serialization.StringSerializer
        # topic 정보 설정
        topic:
            # 알림톡 수신 list
            at-recv-list:
                - recv-at-01
                - recv-at-02
            # 알림톡 발송 map (발송 그룹을 map of list 형태로 추가하여 사용한다)
            at-send-map:
                # default 그룹
                default:
                    - send-at-01
                    - send-at-02
                    - send-at-03
                    - send-at-04
                    - send-at-05
            # 친구톡 수신 list
            ft-recv-list:
                - recv-ft-01
                - recv-ft-02
            # 친구톡 발송 map (발송 그룹을 map of list 형태로 추가하여 사용한다)
            ft-send-map:
                # default 그룹
                default:
                    - send-ft-01
                    - send-ft-02
                    - send-ft-03
                    - send-ft-04
                    - send-ft-05
            # sms mt 수신 list
            smt-recv-list:
                - recv-smt-01
                - recv-smt-02
            # sms mt 발송 map (발송 그룹을 map of list 형태로 추가하여 사용한다)
            smt-send-map:
                # default 그룹
                default:
                    - send-smt-01
                    - send-smt-02
                    - send-smt-03
                    - send-smt-04
                    - send-smt-05
            # lms mt 수신 list
            lmt-recv-list:
                - recv-lmt-01
                - recv-lmt-02
            # lms mt 발송 map (발송 그룹을 map of list 형태로 추가하여 사용한다)
            lmt-send-map:
                # default 그룹
                default:
                    - send-lmt-01
                    - send-lmt-02
                    - send-lmt-03
                    - send-lmt-04
                    - send-lmt-05
spring:
    # redis 설정
    redis:
        # redis 서버 (여러개일 경우, 콤마로 분리)
        host: 211.48.18.171
        # redis 접속 암호
        password: humuson0722
        # redis port
        port: 6379
