imc:
    relay:
        ########################################################################################################
        # 서버 실행 모드 설정
        #
        # RUN-MODE  : [Authorize, Message, Report, Store, All]
        # Authorize : 인증서버 실행
        # Message   : Message 서버 실행
        # Report    : Report 서버 실행
        # Store     : Store 서버 실행
        # All       : 전체 모듈 실행 (Authorize, Message, Report, Store)
        ########################################################################################################
        run-mode: All

---

spring:
    profiles: dev
  
imc:
    relay:
        run-mode: All

---

spring:
    profiles: local
  
imc:
    relay:
        run-mode: Message
