# IMC loadbalancer 설정
imc:
    lb:
        cron:
            load-client-info: 10 */10 * * * *
            load-at-send-profile-info: 40 */10 * * *
            load-at-template-info: 40 */10 * * *
            load-send-group-info: 10 */10 * * * *

---

spring:
    profiles: dev

imc:
    lb:
        cron:
            load-client-info: 10 */10 * * * *
            load-at-send-profile-info: 40 */10 * * *
            load-at-template-info: 40 */10 * * *
            load-send-group-info: 10 */10 * * * *

---

spring:
    profiles: local

imc:
    lb:
        cron:
            load-client-info: 10 */10 * * * *
            load-at-send-profile-info: 40 */10 * * *
            load-at-template-info: 40 */10 * * *
            load-send-group-info: 10 */10 * * * *
            
